# Generated by Django 5.2.4 on 2025-11-02 09:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mime_types', models.JSONField(default=list, help_text='Allowed MIME types')),
                ('is_required', models.BooleanField(default=True)),
                ('max_size_mb', models.PositiveIntegerField(default=10, help_text='Maximum file size in MB')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'document_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='S3 or storage URL')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('REVIEWING', 'Reviewing'), ('NEEDS_REUPLOAD', 'Needs Re-upload'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='RECEIVED', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Review comments')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', 'status'], name='documents_applica_c66735_idx'), models.Index(fields=['status'], name='documents_status_f31a08_idx')],
            },
        ),
    ]
