# Generated by Django 5.2.4 on 2025-11-02 09:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('country', models.CharField(default='South Africa', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('doc_requirements', models.JSONField(default=list, help_text='List of required document types')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'application_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('INTAKE', 'Intake'), ('IN_REVIEW', 'In Review'), ('DOCS_PENDING', 'Documents Pending'), ('READY_TO_SUBMIT', 'Ready to Submit'), ('SUBMITTED', 'Submitted'), ('DHA_PROCESSING', 'DHA Processing'), ('ADDITIONAL_INFO_REQUESTED', 'Additional Info Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='DRAFT', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes not visible to client')),
                ('dha_ref', models.CharField(blank=True, help_text='Department of Home Affairs reference', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.applicationtype')),
            ],
            options={
                'db_table': 'applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=50)),
                ('to_status', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applications.application')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Status histories',
                'db_table': 'status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='applications.application')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['client', 'status'], name='application_client__a9f900_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['assigned_to', 'status'], name='application_assigne_92d6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created_at'], name='application_created_a07231_idx'),
        ),
    ]
